src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shops.urls', namespace='shops'))
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/shops/urls.py
from django.urls import path
from .views import (
    CategoryView,
    HomeView,
    OrderSummaryView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView
)
app_name = 'shops'

urlpatterns = [
    path('category/', CategoryView.as_view(), name='category'),
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    # path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    # path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

src/shops/models.py
# from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    #one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shops:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("shops:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("shops:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    # payment = models.ForeignKey(
    #     'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    # coupon = models.ForeignKey(
    #     'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    # being_delivered = models.BooleanField(default=False)
    # received = models.BooleanField(default=False)
    # refund_requested = models.BooleanField(default=False)
    # refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        # if self.coupon:
        #     total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


# class Payment(models.Model):
#     stripe_charge_id = models.CharField(max_length=50)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL,
#                              on_delete=models.SET_NULL, blank=True, null=True)
#     amount = models.FloatField()
#     timestamp = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.user.username


# class Coupon(models.Model):
#     code = models.CharField(max_length=15)
#     amount = models.FloatField()

#     def __str__(self):
#         return self.code


# class Refund(models.Model):
#     order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     reason = models.TextField()
#     accepted = models.BooleanField(default=False)
#     email = models.EmailField()

#     def __str__(self):
#         return f"{self.pk}"


# def userprofile_receiver(sender, instance, created, *args, **kwargs):
#     if created:
#         userprofile = UserProfile.objects.create(user=instance)

src/templates/basket.html
{% extends "base.html" %} {% load static %} {% load cart_template_tags %}

{% block content %}
<div id="all">
  <div id="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- breadcrumb-->
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li aria-current="page" class="breadcrumb-item active">
                Shopping cart
              </li>
            </ol>
          </nav>
        </div>
        <div id="basket" class="col-lg-9">
          <div class="box">
            <form method="post" action="checkout1.html">
              <h1>Shopping cart</h1>
              <p class="text-muted">
                You currently have {{ request.user | cart_item_count }} item(s)
                in your cart.
              </p>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th colspan="2">Product</th>
                      <th>Quantity</th>
                      <th>Unit price</th>
                      <th>Discount</th>
                      <th colspan="2">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>
                        <a href="#"><img src="{% static 'img/detailsquare.jpg' %}" alt="White Blouse Armani" /></a>
                      </td>
                      <td><a href="#">{{ order_item.item.title }}</a></td>
                      <td>
                        {% comment %}
                        <input type="number" value="{{ order_item.quantity }}" class="form-control" min=0 />
                        {% endcomment %}
                        <a href="{% url 'shops:remove-single-item-from-cart' order_item.item.slug %}">
                          <i class="fa fa-minus mr-2"></i></a>
                        {{ order_item.quantity }}
                        <a href="{% url 'shops:add-to-cart' order_item.item.slug %}"><i class="fa fa-plus ml-2"></i></a>
                      </td>
                      <td>${{ order_item.item.price }}</td>
                      {% if order_item.item.discount_price %}
                      <td>${{ order_item.get_total_discount_item_price }}</td>
                      {% else %}
                      <td>$0.00</td>
                      {% endif %}
                      <td>${{ order_item.get_total_item_price }}</td>
                      <td>
                      <td>${{ order_item.get_total_item_price }}</td>
                      <td>
                        <a href="{% url 'shops:remove-from-cart' order_item.item.slug %}"><i
                            class="fa fa-trash-o"></i></a>
                      </td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td cospan='5'>Your cart is empty</td>
                    </tr>
                    </tr>
                    <!-- /.table-responsive-->
                    <div class="box-footer d-flex justify-content-between flex-column flex-lg-row">
                      <div class="left">
                        <a href="/" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i>
                          Continue
                          shopping</a>
                      </div>
                    </div>
                    {% endfor %}
                  </tbody>
                  {% if object.get_total %}
                  <tfoot>
                    <tr>
                      <th colspan="6">Total</th>
                      <th colspan="2">${{ object.get_total }}</th>
                    </tr>
                  </tfoot>
                  {% endif %}
                </table>
              </div>
              {% if object.get_total %}
              <!-- /.table-responsive-->
              <div class="box-footer d-flex justify-content-between flex-column flex-lg-row">
                <div class="left">
                  <a href="/product" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Continue
                    shopping</a>
                </div>
                <div class="right">
                  <a class="btn btn-outline-secondary">
                    <i class="fa fa-refresh"></i> Update cart
                  </a>
                  <a type="submit" class="btn btn-primary" href='/checkout/'>
                    Proceed to checkout <i class="fa fa-chevron-right"></i>
                  </a>
                </div>
              </div>
              {% endif %}
            </form>
          </div>
          <!-- /.box-->

        </div>
        <!-- /.col-lg-9-->
        <div class="col-lg-3">
          <div id="order-summary" class="box">
            <div class="box-header">
              <h3 class="mb-0">Order summary</h3>
            </div>
            <p class="text-muted">
              Shipping and additional costs are calculated based on the values
              you have entered.
            </p>
            <div class="table-responsive">
              <table class="table">
                <tbody>
                  <tr>
                    <td>Order subtotal</td>
                    <th>${{ object.get_total }}</th>
                  </tr>
                  <tr>
                    <td>Shipping and handling</td>
                    <th>$10.00</th>
                  </tr>
                  <tr>
                    <td>Tax</td>
                    <th>$0.00</th>
                  </tr>
                  <tr class="total">
                    <td>Total</td>
                    <th>$456.00</th>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="box">
            <div class="box-header">
              <h4 class="mb-0">Coupon code</h4>
            </div>
            <p class="text-muted">
              If you have a coupon code, please enter it in the box below.
            </p>
            <form>
              <div class="input-group">
                <input type="text" class="form-control" /><span class="input-group-append">
                  <button type="button" class="btn btn-primary">
                    <i class="fa fa-gift"></i></button></span>
              </div>
              <!-- /input-group-->
            </form>
          </div>
        </div>
        <!-- /.col-md-3-->
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/templates/checkout.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}

{% block content %}
<div id="all">
  <div id="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- breadcrumb-->
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li aria-current="page" class="breadcrumb-item active">Checkout - Address</li>
            </ol>
          </nav>
        </div>
        <div id="checkout" class="col-lg-9">

          <div class="box">
            <form method="POST" action="">
              {% csrf_token %}
              <h1>Checkout - Address</h1>
              <div class="nav flex-column flex-md-row nav-pills text-center"><a href="checkout1.html"
                  class="nav-link flex-sm-fill text-sm-center active"> <i class="fa fa-map-marker"> </i>Address</a><a
                  href="#" class="nav-link flex-sm-fill text-sm-center disabled"> <i class="fa fa-truck"> </i>Delivery
                  Method</a><a href="#" class="nav-link flex-sm-fill text-sm-center disabled"> <i class="fa fa-money">
                  </i>Payment Method</a><a href="#" class="nav-link flex-sm-fill text-sm-center disabled"> <i
                    class="fa fa-eye"> </i>Order Review</a></div>
              <div class="content py-3">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="company">Street1</label>
                      {{ form.shipping_address }}
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label for="street">Street2</label>
                      {{ form.shipping_address2}}
                    </div>
                  </div>
                </div>
                <!-- /.row-->
                <div class="row">
                  <div class="col-md-6 col-lg-3">
                    <div class="form-group">
                      <label for="zip">ZIP</label>
                      {{ form.shipping_zip }}
                    </div>
                  </div>
                  <div class="col-md-6 col-lg-3">
                    <div class="form-group">
                      <label for="state">State</label>
                      <select id="state" class="form-control"></select>
                    </div>
                  </div>
                  <div class="col-md-6 col-lg-3">
                    <div class="form-group">
                      <label for="country">Country</label>
                      {{ form.shipping_country }}
                    </div>
                  </div>
                </div>
                <!-- /.row-->

                <div class="custom-control custom-checkbox mb-2">
                  <input {%if form.same_shipping_address.value %}checked{% endif %} type="checkbox"
                    class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my
                    shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping"
                    id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping
                    address</label>
                </div>
              </div>
              <div class="content py-3">
                <div class="row">
                  {% for value, name in form.fields.payment_option.choices %}
                  <div class="col-md-6">
                    <div class="box payment-method">
                      <h4>{{ name }}</h4>
                      <p>We like it all.</p>
                      <div class="box-footer text-center">
                        <input type="radio" id="{{ name }}" name="payment_option" value="{{ value }}">
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
                <!-- /.row-->
              </div>
          </div>
          <div class="box-footer d-flex justify-content-between"><a href="basket.html"
              class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i>Back to Basket</a>
            <button type="submit" class="btn btn-primary">Continue to Delivery Method<i
                class="fa fa-chevron-right"></i></button>
          </div>
          </form>
        </div>
        <!-- /.box-->
      </div>
      <!-- /.col-lg-9-->
      <div class="col-lg-3">
        <div id="order-summary" class="card">
          <div class="card-header">
            <h3 class="mt-4 mb-4">Order summary</h3>
          </div>
          <div class="card-body">
            <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.
            </p>
            <div class="table-responsive">
              <table class="table">
                <tbody>
                  <tr>
                    <td>Order subtotal</td>
                    <th>$446.00</th>
                  </tr>
                  <tr>
                    <td>Shipping and handling</td>
                    <th>$10.00</th>
                  </tr>
                  <tr>
                    <td>Tax</td>
                    <th>$0.00</th>
                  </tr>
                  <tr class="total">
                    <td>Total</td>
                    <th>$456.00</th>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.col-lg-3-->
    </div>
  </div>
</div>
</div>


{% endblock content %}

src/templates/checkout3.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}

{% block content %}
<div id="all">
  <div id="content">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- breadcrumb-->
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li aria-current="page" class="breadcrumb-item active">Checkout - Payment method</li>
            </ol>
          </nav>
        </div>
        <div id="checkout" class="col-lg-9">

          <div class="box">
            <form method="POST" action="">
              {% csrf_token %}
              <h1>Checkout - Payment method</h1>
              <div class="nav flex-column flex-sm-row nav-pills"><a href="checkout1.html"
                  class="nav-link flex-sm-fill text-sm-center"> <i class="fa fa-map-marker"> </i>Address</a><a
                  href="checkout2.html" class="nav-link flex-sm-fill text-sm-center"> <i class="fa fa-truck">
                  </i>Delivery Method</a><a href="checkout3.html" class="nav-link flex-sm-fill text-sm-center active">
                  <i class="fa fa-money"> </i>Payment Method</a><a href="#"
                  class="nav-link flex-sm-fill text-sm-center disabled"> <i class="fa fa-eye"> </i>Order Review</a>
              </div>
              <div class="content py-3">
                <div class="row">
                  <div class="col-md-6">
                    <div class="box payment-method">
                      <h4>Paypal</h4>
                      <p>We like it all.</p>
                      <div class="box-footer text-center">
                        <input type="radio" name="payment" value="payment1">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="box payment-method">
                      <h4>Payment gateway</h4>
                      <p>VISA and Mastercard only.</p>
                      <div class="box-footer text-center">
                        <input type="radio" name="payment" value="payment2">
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="box payment-method">
                      <h4>Cash on delivery</h4>
                      <p>You pay when you get it.</p>
                      <div class="box-footer text-center">
                        <input type="radio" name="payment" value="payment3">
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.row-->
              </div>
              <!-- /.content-->
              <div class="box-footer d-flex justify-content-between"><a href="checkout2.html"
                  class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i>Back to Shipping Method</a>
                <button type="submit" class="btn btn-primary">Continue to Order Review<i
                    class="fa fa-chevron-right"></i></button>
              </div>
            </form>
            <!-- /.box-->
          </div>
        </div>
        <!-- /.col-lg-9-->
        <div class="col-lg-3">
          <div id="order-summary" class="card">
            <div class="card-header">
              <h3 class="mt-4 mb-4">Order summary</h3>
            </div>
            <div class="card-body">
              <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.
              </p>
              <div class="table-responsive">
                <table class="table">
                  <tbody>
                    <tr>
                      <td>Order subtotal</td>
                      <th>$446.00</th>
                    </tr>
                    <tr>
                      <td>Shipping and handling</td>
                      <th>$10.00</th>
                    </tr>
                    <tr>
                      <td>Tax</td>
                      <th>$0.00</th>
                    </tr>
                    <tr class="total">
                      <td>Total</td>
                      <th>$456.00</th>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <!-- /.col-lg-3-->
      </div>
    </div>
  </div>
</div>


{% endblock content %}

src/templates/home.html
{% extends "base.html" %} {% load static %} {% block content %}
<div id="all">
  <div id="content">
    <!--
      *** HOT PRODUCT SLIDESHOW ***
      _________________________________________________________
      -->
    <div id="hot">
      <div class="box py-4">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h2 class="mb-0">Hot this week</h2>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="product-slider owl-carousel owl-theme">
          {% for item in object_list %}
          <div class="item">
            <div class="product">
              <div class="flip-container">
                <div class="flipper">
                  <div class="front">
                    <a href="detail.html"
                      ><img
                        src="{% static 'img/product1.jpg' %}"
                        alt=""
                        class="img-fluid"
                    /></a>
                  </div>
                  <div class="back">
                    <a href="detail.html"
                      ><img
                        src="{% static 'img/product1_2.jpg' %}"
                        alt=""
                        class="img-fluid"
                    /></a>
                  </div>
                </div>
              </div>
              <a href="detail.html" class="invisible"
                ><img
                  src="{% static 'img/product1.jpg' %}"
                  alt=""
                  class="img-fluid"
              /></a>
              <div class="text">
                <p>{{ item.get_category_display }}</p>
                <h3>
                  <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                </h3>
                <p class="price"><del></del>${{ item.price }}</p>
              </div>
              <!-- /.text-->
              <div class="ribbon sale">
                <div class="theribbon">SALE</div>
                <div class="ribbon-background"></div>
              </div>
              <!-- /.ribbon-->
              <div class="ribbon new">
                <div class="theribbon">NEW</div>
                <div class="ribbon-background"></div>
              </div>
              <!-- /.ribbon-->
              <div class="ribbon gift">
                <div class="theribbon">GIFT</div>
                <div
                  class="ribbon-background btn-{{ item.get_label_display }}"
                ></div>
              </div>
              <!-- /.ribbon-->
            </div>
            <!-- /.product-->
          </div>
          {% endfor %}
          <!-- /.product-slider-->
        </div>
        <!-- /.container-->
        <div class="pages">
          <!-- <p class="loadMore">
            <a href="#" class="btn btn-primary btn-lg"
              ><i class="fa fa-chevron-down"></i> Load more</a
            >
          </p> -->
          {% if is_paginated %}
          <nav
            aria-label="Page navigation example"
            class="d-flex justify-content-center"
          >
            <ul class="pagination">
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a
                  href="?page={{ page_obj.previous_page_number }}"
                  aria-label="Previous"
                  class="page-link"
                  ><span aria-hidden="true">«</span
                  ><span class="sr-only">Previous</span></a
                >
              </li>
              {% endif %}
              <li class="page-item active">
                <a href="?page={{ page_obj.number }}" class="page-link">
                  {{ page_obj.number }}
                </a>
              </li>
              <li class="page-item">
                {% if page_obj.has_next %}
                <a
                  href="?page={{ page_obj.next_page_number }}"
                  aria-label="Next"
                  class="page-link"
                  ><span aria-hidden="true">»</span
                  ><span class="sr-only">Next</span></a
                >
              </li>
              {% endif %}
            </ul>
          </nav>
          {% endif %}
        </div>
      </div>
      <!-- /#hot-->
      <!-- *** HOT END ***-->
    </div>
    <!--
      *** GET INSPIRED ***
      _________________________________________________________
      -->

    <div class="container">
      <div class="col-md-12">
        <div id="blog-homepage" class="row">
          <div class="col-sm-6">
            <div class="post">
              <h4><a href="post.html">Fashion now</a></h4>
              <p class="author-category">
                By <a href="#">John Slim</a> in <a href="">Fashion and style</a>
              </p>
              <hr />
              <p class="intro">
                Pellentesque habitant morbi tristique senectus et netus et
                malesuada fames ac turpis egestas. Vestibulum tortor quam,
                feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu
                libero sit amet quam egestas semper. Aenean ultricies mi vitae
                est. Mauris placerat eleifend leo.
              </p>
              <p class="read-more">
                <a href="post.html" class="btn btn-primary">Continue reading</a>
              </p>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="post">
              <h4><a href="post.html">Who is who - example blog post</a></h4>
              <p class="author-category">
                By <a href="#">John Slim</a> in <a href="">About Minimal</a>
              </p>
              <hr />
              <p class="intro">
                Pellentesque habitant morbi tristique senectus et netus et
                malesuada fames ac turpis egestas. Vestibulum tortor quam,
                feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu
                libero sit amet quam egestas semper. Aenean ultricies mi vitae
                est. Mauris placerat eleifend leo.
              </p>
              <p class="read-more">
                <a href="post.html" class="btn btn-primary">Continue reading</a>
              </p>
            </div>
          </div>
        </div>
        <!-- /#blog-homepage-->
      </div>
    </div>
    <!-- /.container-->
    <!-- *** BLOG HOMEPAGE END ***-->
  </div>
</div>
{% endblock content %}

src/templates/scripts.html
{% load static %}
<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>